version: '2.4'
services:
  db-docker:
    container_name: 'mongodb'
    image: 'mongo:4.4.4'
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

  mongo-express:
    container_name: 'mongo-express'
    image: 'mongo-express'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db-docker
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      db-docker:
        condition: service_healthy

  yelpcamp:
    container_name: 'yelpcamp-ejs'
    image: 'jchengdeveng/yelpcamp-ejs'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        CREATED_DATE: '$BUILD_DATE'
        SOURCE_COMMIT: '$COMMIT'
    ports:
      - 8080:8080
    volumes:
      - .:/node/app
      - /node/node_modules
    environment:
      - NODE_VERSION=14.16.0
      - NODE_ENV=development
      - DEBUG=*,-request:*
      - DATABASEURL=mongodb://username:password@db-docker/yelpcamp_123
      - PORT=8080
    env_file:
      - ./.env # create untracked file with remote DB URI
    depends_on:
      db-docker:
        condition: service_healthy
