version: '2.4'
services:
  db-docker:
    container_name: 'mongodb'
    image: 'mongo:4.4.4'
    ports:
      - 27017:27017
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

  mongo-seed:
    image: 'jchengdeveng/mongo-seed'
    build:
      context: ./seeds
      dockerfile: Dockerfile
    environment:
      MONGO_DB: db-docker
      DATABASE_NAME: yelpcamp_123
      USERNAME: username # using root (wrong)
      PASSWORD: password # using root (wrong)
    depends_on:
      db-docker:
        condition: service_healthy

  mongo-express:
    container_name: 'mongo-express'
    image: 'mongo-express'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db-docker
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      db-docker:
        condition: service_healthy

  yelpcamp:
    container_name: 'yelpcamp-ejs'
    image: 'jchengdeveng/yelpcamp-ejs'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        CREATED_DATE: '$BUILD_DATE'
        SOURCE_COMMIT: '$COMMIT'
    ports:
      - 8080:8080
    volumes:
      - .:/node/app
      - /node/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://db-docker:27017/yelpcamp_123
      - PORT=8080
    env_file:
      - ./.env # create untracked file with remote DB URI
    depends_on:
      mongo-seed:
        condition: service_started
