version: '2.4'
services:
  db-docker:
    container_name: 'mongodb'
    image: 'mongo:4.4.4'
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet 

  mongo-express:
    container_name: 'mongo-express'
    image: 'mongo-express'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db-docker
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      db-docker: 
        condition: service_healthy

